artifacts_root: artifacts


data_ingestion:
  dataset_name: "alexfabbri/multi_news"
  arrow_dataset_dir: artifacts/data


data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_folders: ["train", "test", "validation", "dataset_dict.json"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data
  tokenizer_name: google/pegasus-cnn_dailymail


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/dataset
  model_ckpt: google/pegasus-cnn_dailymail
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv
