artifacts_root: artifacts


data_ingestion:
  dataset_name: "alexfabbri/multi_news"
  arrow_dataset_dir: artifacts/data


data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_folders: ["train", "test", "validation", "dataset_dict.json"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data
  tokenizer_name: google/pegasus-cnn_dailymail
